baseURL = "http://example.org/"
languageCode = "en-us"
title = "Foundations of Interactive Media"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[permalinks]
  blog = "/:section/:filename/"

[menu]
  [[menu.main]]
    name = "Assignments"
    url = "/assignment/"
    weight = 1
  [[menu.main]]
    name = "Resources"
    url = "/resource/"
    weight = 2